// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	formDataBodySerializer,
	type Options as Options2,
	type TDataShape,
	urlSearchParamsBodySerializer
} from './client';
import { client } from './client.gen';
import type {
	CeleryResultTaskIdGetData,
	CeleryResultTaskIdGetErrors,
	CeleryResultTaskIdGetResponses,
	ExpiredTokenGetData,
	ExpiredTokenGetErrors,
	ExpiredTokenGetResponses,
	ForgotPasswordPostData,
	ForgotPasswordPostErrors,
	ForgotPasswordPostResponses,
	HealthcheckGetData,
	HealthcheckGetResponses,
	LoginPostData,
	LoginPostErrors,
	LoginPostResponses,
	LoginRefreshTokenPostData,
	LoginRefreshTokenPostErrors,
	LoginRefreshTokenPostResponses,
	ResetPasswordTokenPostData,
	ResetPasswordTokenPostErrors,
	ResetPasswordTokenPostResponses,
	StorageUploadMultiplePostData,
	StorageUploadMultiplePostErrors,
	StorageUploadMultiplePostResponses,
	StorageUploadPostData,
	StorageUploadPostErrors,
	StorageUploadPostResponses,
	UsersMeDeleteData,
	UsersMeDeleteErrors,
	UsersMeDeleteResponses,
	UsersMeGetData,
	UsersMeGetErrors,
	UsersMeGetResponses,
	UsersMePasswordPatchData,
	UsersMePasswordPatchErrors,
	UsersMePasswordPatchResponses,
	UsersMePatchData,
	UsersMePatchErrors,
	UsersMePatchResponses,
	UsersSignupPostData,
	UsersSignupPostErrors,
	UsersSignupPostResponses,
	VerifyAccountTokenPutData,
	VerifyAccountTokenPutErrors,
	VerifyAccountTokenPutResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginPostData, ThrowOnError>
) =>
	(options.client ?? client).post<LoginPostResponses, LoginPostErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		url: '/api/login/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Refresh Access Token
 *
 * User refresh token to get a new access token
 */
export const loginRefreshTokenPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginRefreshTokenPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		LoginRefreshTokenPostResponses,
		LoginRefreshTokenPostErrors,
		ThrowOnError
	>({ url: '/api/login/refresh-token/', ...options });

/**
 * Verify Account
 */
export const verifyAccountTokenPut = <ThrowOnError extends boolean = false>(
	options: Options<VerifyAccountTokenPutData, ThrowOnError>
) =>
	(options.client ?? client).put<
		VerifyAccountTokenPutResponses,
		VerifyAccountTokenPutErrors,
		ThrowOnError
	>({ url: '/api/verify/account/{token}/', ...options });

/**
 * Forgot Password
 *
 * Update own passowrd
 */
export const forgotPasswordPost = <ThrowOnError extends boolean = false>(
	options: Options<ForgotPasswordPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		ForgotPasswordPostResponses,
		ForgotPasswordPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: '/api/forgot/password/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Reset Password
 *
 * Reset password
 */
export const resetPasswordTokenPost = <ThrowOnError extends boolean = false>(
	options: Options<ResetPasswordTokenPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		ResetPasswordTokenPostResponses,
		ResetPasswordTokenPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: '/api/reset/password/{token}/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Is Token Expired
 */
export const expiredTokenGet = <ThrowOnError extends boolean = false>(
	options: Options<ExpiredTokenGetData, ThrowOnError>
) =>
	(options.client ?? client).get<ExpiredTokenGetResponses, ExpiredTokenGetErrors, ThrowOnError>({
		url: '/api/expired/{token}/',
		...options
	});

/**
 * Register User
 *
 * Register a new User
 */
export const usersSignupPost = <ThrowOnError extends boolean = false>(
	options: Options<UsersSignupPostData, ThrowOnError>
) =>
	(options.client ?? client).post<UsersSignupPostResponses, UsersSignupPostErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		url: '/api/users/signup/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersMeDelete = <ThrowOnError extends boolean = false>(
	options?: Options<UsersMeDeleteData, ThrowOnError>
) =>
	(options?.client ?? client).delete<UsersMeDeleteResponses, UsersMeDeleteErrors, ThrowOnError>({
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/users/me/',
		...options
	});

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersMeGet = <ThrowOnError extends boolean = false>(
	options?: Options<UsersMeGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<UsersMeGetResponses, UsersMeGetErrors, ThrowOnError>({
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/users/me/',
		...options
	});

/**
 * Update User Me
 *
 * Update own user
 */
export const usersMePatch = <ThrowOnError extends boolean = false>(
	options: Options<UsersMePatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<UsersMePatchResponses, UsersMePatchErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/users/me/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersMePasswordPatch = <ThrowOnError extends boolean = false>(
	options: Options<UsersMePasswordPatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<
		UsersMePasswordPatchResponses,
		UsersMePasswordPatchErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/users/me/password/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Get Result
 */
export const celeryResultTaskIdGet = <ThrowOnError extends boolean = false>(
	options: Options<CeleryResultTaskIdGetData, ThrowOnError>
) =>
	(options.client ?? client).get<
		CeleryResultTaskIdGetResponses,
		CeleryResultTaskIdGetErrors,
		ThrowOnError
	>({ url: '/api/celery/result/{task_id}/', ...options });

/**
 * Upload File
 */
export const storageUploadPost = <ThrowOnError extends boolean = false>(
	options: Options<StorageUploadPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		StorageUploadPostResponses,
		StorageUploadPostErrors,
		ThrowOnError
	>({
		...formDataBodySerializer,
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/storage/upload/',
		...options,
		headers: {
			'Content-Type': null,
			...options.headers
		}
	});

/**
 * Upload Multiple
 */
export const storageUploadMultiplePost = <ThrowOnError extends boolean = false>(
	options: Options<StorageUploadMultiplePostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		StorageUploadMultiplePostResponses,
		StorageUploadMultiplePostErrors,
		ThrowOnError
	>({
		...formDataBodySerializer,
		url: '/api/storage/upload/multiple/',
		...options,
		headers: {
			'Content-Type': null,
			...options.headers
		}
	});

/**
 * Health Check
 */
export const healthcheckGet = <ThrowOnError extends boolean = false>(
	options?: Options<HealthcheckGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<HealthcheckGetResponses, unknown, ThrowOnError>({
		url: '/healthcheck/',
		...options
	});
