// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthLoginPostData, AuthLoginPostResponses, CeleryResultTaskIdGetData, CeleryResultTaskIdGetErrors, CeleryResultTaskIdGetResponses, CelerySequentialCeleryGetData, CelerySequentialCeleryGetResponses, CelerySequentialGetData, CelerySequentialGetResponses, HealthcheckGetData, HealthcheckGetResponses, UsersSignupPostData, UsersSignupPostErrors, UsersSignupPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const authLoginPost = <ThrowOnError extends boolean = false>(options?: Options<AuthLoginPostData, ThrowOnError>) => (options?.client ?? client).post<AuthLoginPostResponses, unknown, ThrowOnError>({ url: '/api/auth/login/', ...options });

/**
 * Sequential Task
 */
export const celerySequentialGet = <ThrowOnError extends boolean = false>(options?: Options<CelerySequentialGetData, ThrowOnError>) => (options?.client ?? client).get<CelerySequentialGetResponses, unknown, ThrowOnError>({ url: '/api/celery/sequential/', ...options });

/**
 * Sequential Task Celery
 */
export const celerySequentialCeleryGet = <ThrowOnError extends boolean = false>(options?: Options<CelerySequentialCeleryGetData, ThrowOnError>) => (options?.client ?? client).get<CelerySequentialCeleryGetResponses, unknown, ThrowOnError>({ url: '/api/celery/sequential/celery/', ...options });

/**
 * Get Result
 */
export const celeryResultTaskIdGet = <ThrowOnError extends boolean = false>(options: Options<CeleryResultTaskIdGetData, ThrowOnError>) => (options.client ?? client).get<CeleryResultTaskIdGetResponses, CeleryResultTaskIdGetErrors, ThrowOnError>({ url: '/api/celery/result/{task_id}/', ...options });

/**
 * Register User
 *
 * Register a new User
 */
export const usersSignupPost = <ThrowOnError extends boolean = false>(options: Options<UsersSignupPostData, ThrowOnError>) => (options.client ?? client).post<UsersSignupPostResponses, UsersSignupPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/users/signup/',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Health Check
 */
export const healthcheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthcheckGetData, ThrowOnError>) => (options?.client ?? client).get<HealthcheckGetResponses, unknown, ThrowOnError>({ url: '/healthcheck/', ...options });
