// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type Options as Options2,
	type TDataShape,
	urlSearchParamsBodySerializer
} from './client';
import { client } from './client.gen';
import type {
	ExpiredTokenGetData,
	ExpiredTokenGetErrors,
	ExpiredTokenGetResponses,
	ForgotPasswordPostData,
	ForgotPasswordPostErrors,
	ForgotPasswordPostResponses,
	HealthcheckGetData,
	HealthcheckGetResponses,
	LoginPostData,
	LoginPostErrors,
	LoginPostResponses,
	ResetPasswordTokenPostData,
	ResetPasswordTokenPostErrors,
	ResetPasswordTokenPostResponses,
	SignupPostData,
	SignupPostErrors,
	SignupPostResponses,
	StorageFolderFolderIdPatchData,
	StorageFolderFolderIdPatchErrors,
	StorageFolderFolderIdPatchResponses,
	StorageFolderIdPostData,
	StorageFolderIdPostErrors,
	StorageFolderIdPostResponses,
	StorageFolderRootGetData,
	StorageFolderRootGetErrors,
	StorageFolderRootGetResponses,
	StorageFolderRootPostData,
	StorageFolderRootPostErrors,
	StorageFolderRootPostResponses,
	StorageFoldersFolderIdGetData,
	StorageFoldersFolderIdGetErrors,
	StorageFoldersFolderIdGetResponses,
	UsersMeGetData,
	UsersMeGetErrors,
	UsersMeGetResponses,
	VerifyAccountTokenPutData,
	VerifyAccountTokenPutErrors,
	VerifyAccountTokenPutResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Sign Up
 */
export const signupPost = <ThrowOnError extends boolean = false>(
	options: Options<SignupPostData, ThrowOnError>
) =>
	(options.client ?? client).post<SignupPostResponses, SignupPostErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		url: '/api/v1/signup/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Log In
 */
export const loginPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginPostData, ThrowOnError>
) =>
	(options.client ?? client).post<LoginPostResponses, LoginPostErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		url: '/api/v1/login/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Verify Account
 */
export const verifyAccountTokenPut = <ThrowOnError extends boolean = false>(
	options: Options<VerifyAccountTokenPutData, ThrowOnError>
) =>
	(options.client ?? client).put<
		VerifyAccountTokenPutResponses,
		VerifyAccountTokenPutErrors,
		ThrowOnError
	>({ url: '/api/v1/verify/account/{token}/', ...options });

/**
 * Forgot Password
 */
export const forgotPasswordPost = <ThrowOnError extends boolean = false>(
	options: Options<ForgotPasswordPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		ForgotPasswordPostResponses,
		ForgotPasswordPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: '/api/v1/forgot/password/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Reset Password
 */
export const resetPasswordTokenPost = <ThrowOnError extends boolean = false>(
	options: Options<ResetPasswordTokenPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		ResetPasswordTokenPostResponses,
		ResetPasswordTokenPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: '/api/v1/reset/password/{token}/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Is Token Expired
 */
export const expiredTokenGet = <ThrowOnError extends boolean = false>(
	options: Options<ExpiredTokenGetData, ThrowOnError>
) =>
	(options.client ?? client).get<ExpiredTokenGetResponses, ExpiredTokenGetErrors, ThrowOnError>({
		url: '/api/v1/expired/{token}/',
		...options
	});

/**
 * Get User Me
 */
export const usersMeGet = <ThrowOnError extends boolean = false>(
	options?: Options<UsersMeGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<UsersMeGetResponses, UsersMeGetErrors, ThrowOnError>({
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/v1/users/me/',
		...options
	});

/**
 * Get Folders In Folder
 */
export const storageFoldersFolderIdGet = <ThrowOnError extends boolean = false>(
	options: Options<StorageFoldersFolderIdGetData, ThrowOnError>
) =>
	(options.client ?? client).get<
		StorageFoldersFolderIdGetResponses,
		StorageFoldersFolderIdGetErrors,
		ThrowOnError
	>({ url: '/api/v1/storage/folders/{folder_id}/', ...options });

/**
 * Get Root Folder
 */
export const storageFolderRootGet = <ThrowOnError extends boolean = false>(
	options?: Options<StorageFolderRootGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<
		StorageFolderRootGetResponses,
		StorageFolderRootGetErrors,
		ThrowOnError
	>({
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/v1/storage/folder/root/',
		...options
	});

/**
 * Create Root Folder
 */
export const storageFolderRootPost = <ThrowOnError extends boolean = false>(
	options?: Options<StorageFolderRootPostData, ThrowOnError>
) =>
	(options?.client ?? client).post<
		StorageFolderRootPostResponses,
		StorageFolderRootPostErrors,
		ThrowOnError
	>({
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/v1/storage/folder/root/',
		...options
	});

/**
 * Create Folder
 */
export const storageFolderIdPost = <ThrowOnError extends boolean = false>(
	options: Options<StorageFolderIdPostData, ThrowOnError>
) =>
	(options.client ?? client).post<
		StorageFolderIdPostResponses,
		StorageFolderIdPostErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/v1/storage/{folder_id}/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Update Folder
 */
export const storageFolderFolderIdPatch = <ThrowOnError extends boolean = false>(
	options: Options<StorageFolderFolderIdPatchData, ThrowOnError>
) =>
	(options.client ?? client).patch<
		StorageFolderFolderIdPatchResponses,
		StorageFolderFolderIdPatchErrors,
		ThrowOnError
	>({
		...urlSearchParamsBodySerializer,
		url: '/api/v1/storage/folder/{folder_id}/',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Health Check
 */
export const healthcheckGet = <ThrowOnError extends boolean = false>(
	options?: Options<HealthcheckGetData, ThrowOnError>
) =>
	(options?.client ?? client).get<HealthcheckGetResponses, unknown, ThrowOnError>({
		url: '/healthcheck/',
		...options
	});
