// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_forgot_password_api_v1_forgot_password__post
 */
export type BodyForgotPasswordApiV1ForgotPasswordPost = {
	/**
	 * Email
	 */
	email: string;
};

/**
 * Body_log_in_api_v1_login__post
 */
export type BodyLogInApiV1LoginPost = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * Body_reset_password_api_v1_reset_password__token___post
 */
export type BodyResetPasswordApiV1ResetPasswordTokenPost = {
	/**
	 * New Password
	 */
	new_password: string;
};

/**
 * HTTPMessage
 */
export type HttpMessage = {
	/**
	 * Msg
	 */
	msg: string;
	/**
	 * Loc
	 */
	loc?: string | null;
	/**
	 * Meta
	 */
	meta?: {
		[key: string]: unknown;
	} | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
	/**
	 * Title
	 */
	title: string;
	/**
	 * Description
	 */
	description: string;
	/**
	 * Version
	 */
	version: string;
};

/**
 * Token
 */
export type Token = {
	/**
	 * Access Token
	 */
	access_token: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * First Name
	 */
	first_name: string;
	/**
	 * Last Name
	 */
	last_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Is Verified
	 */
	is_verified?: boolean;
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean;
	/**
	 * Id
	 */
	id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
	/**
	 * First Name
	 */
	first_name: string;
	/**
	 * Last Name
	 */
	last_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type SignupPostData = {
	body: UserRegister;
	path?: never;
	query?: {
		/**
		 * Locale
		 */
		locale?: string;
	};
	url: '/api/v1/signup/';
};

export type SignupPostErrors = {
	/**
	 * Conflict
	 */
	409: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SignupPostError = SignupPostErrors[keyof SignupPostErrors];

export type SignupPostResponses = {
	/**
	 * Response Sign Up Api V1 Signup  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type SignupPostResponse = SignupPostResponses[keyof SignupPostResponses];

export type LoginPostData = {
	body: BodyLogInApiV1LoginPost;
	path?: never;
	query?: never;
	url: '/api/v1/login/';
};

export type LoginPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginPostError = LoginPostErrors[keyof LoginPostErrors];

export type LoginPostResponses = {
	/**
	 * Successful Response
	 */
	200: Token;
};

export type LoginPostResponse = LoginPostResponses[keyof LoginPostResponses];

export type VerifyAccountTokenPutData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/verify/account/{token}/';
};

export type VerifyAccountTokenPutErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type VerifyAccountTokenPutError =
	VerifyAccountTokenPutErrors[keyof VerifyAccountTokenPutErrors];

export type VerifyAccountTokenPutResponses = {
	/**
	 * Response Verify Account Api V1 Verify Account  Token   Put
	 *
	 * Successful Response
	 */
	200: string;
};

export type VerifyAccountTokenPutResponse =
	VerifyAccountTokenPutResponses[keyof VerifyAccountTokenPutResponses];

export type ForgotPasswordPostData = {
	body: BodyForgotPasswordApiV1ForgotPasswordPost;
	path?: never;
	query?: {
		/**
		 * Locale
		 */
		locale?: string;
	};
	url: '/api/v1/forgot/password/';
};

export type ForgotPasswordPostErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ForgotPasswordPostError = ForgotPasswordPostErrors[keyof ForgotPasswordPostErrors];

export type ForgotPasswordPostResponses = {
	/**
	 * Response Forgot Password Api V1 Forgot Password  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ForgotPasswordPostResponse =
	ForgotPasswordPostResponses[keyof ForgotPasswordPostResponses];

export type ResetPasswordTokenPostData = {
	body: BodyResetPasswordApiV1ResetPasswordTokenPost;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/reset/password/{token}/';
};

export type ResetPasswordTokenPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ResetPasswordTokenPostError =
	ResetPasswordTokenPostErrors[keyof ResetPasswordTokenPostErrors];

export type ResetPasswordTokenPostResponses = {
	/**
	 * Response Reset Password Api V1 Reset Password  Token   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ResetPasswordTokenPostResponse =
	ResetPasswordTokenPostResponses[keyof ResetPasswordTokenPostResponses];

export type ExpiredTokenGetData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/expired/{token}/';
};

export type ExpiredTokenGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ExpiredTokenGetError = ExpiredTokenGetErrors[keyof ExpiredTokenGetErrors];

export type ExpiredTokenGetResponses = {
	/**
	 * Response Is Token Expired Api V1 Expired  Token   Get
	 *
	 * Successful Response
	 */
	200: boolean;
};

export type ExpiredTokenGetResponse = ExpiredTokenGetResponses[keyof ExpiredTokenGetResponses];

export type UsersMeGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/users/me/';
};

export type UsersMeGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type UsersMeGetError = UsersMeGetErrors[keyof UsersMeGetErrors];

export type UsersMeGetResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic;
};

export type UsersMeGetResponse = UsersMeGetResponses[keyof UsersMeGetResponses];

export type HealthcheckGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/healthcheck/';
};

export type HealthcheckGetResponses = {
	/**
	 * Successful Response
	 */
	200: HealthCheck;
};

export type HealthcheckGetResponse = HealthcheckGetResponses[keyof HealthcheckGetResponses];
