// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AvailableSpace
 */
export type AvailableSpace = {
	/**
	 * Total
	 */
	total: number;
	/**
	 * Used
	 */
	used: number;
	/**
	 * Free
	 */
	free: number;
};

/**
 * Body_forgot_password_api_forgot_password__post
 */
export type BodyForgotPasswordApiForgotPasswordPost = {
	/**
	 * Email
	 */
	email: string;
};

/**
 * Body_login_api_login__post
 */
export type BodyLoginApiLoginPost = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * Body_register_user_api_users_signup__post
 */
export type BodyRegisterUserApiUsersSignupPost = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Username
	 */
	username: string;
};

/**
 * Body_reset_password_api_reset_password__token___post
 */
export type BodyResetPasswordApiResetPasswordTokenPost = {
	/**
	 * New Password
	 */
	new_password: string;
};

/**
 * Body_upload_multiple_api_storage_upload_multiple__path___post
 */
export type BodyUploadMultipleApiStorageUploadMultiplePathPost = {
	/**
	 * Files
	 */
	files: Array<Blob | File>;
};

/**
 * FileFolderPublic
 */
export type FileFolderPublic = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * Size
	 */
	size: number;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Path
	 */
	path: string;
	/**
	 * Lastmodified
	 */
	lastModified: string;
};

/**
 * FileFolderStatus
 */
export type FileFolderStatus = 'pending' | 'uploaded' | 'failed' | 'deleted';

/**
 * HTTPMessage
 */
export type HttpMessage = {
	/**
	 * Msg
	 */
	msg: string;
	/**
	 * Loc
	 */
	loc?: string | null;
	/**
	 * Meta
	 */
	meta?: {
		[key: string]: unknown;
	} | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Version
	 */
	version: string;
	/**
	 * Description
	 */
	description: string;
};

/**
 * Tokens
 */
export type Tokens = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Refresh Token
	 */
	refresh_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
	/**
	 * Current Password
	 */
	current_password: string;
	/**
	 * New Password
	 */
	new_password: string;
};

/**
 * UploadFiles
 */
export type UploadFiles = {
	/**
	 * Uploaded
	 */
	uploaded: Array<string>;
	/**
	 * Errors
	 */
	errors: Array<string>;
	/**
	 * Total Uploaded
	 */
	total_uploaded: number;
	/**
	 * Total Errors
	 */
	total_errors: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Is Verified
	 */
	is_verified?: boolean;
	/**
	 * Is Superuser
	 */
	is_superuser: boolean;
	/**
	 * Id
	 */
	id: string;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
	/**
	 * Email
	 */
	email?: string | null;
	/**
	 * Username
	 */
	username?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

export type LoginPostData = {
	body: BodyLoginApiLoginPost;
	path?: never;
	query?: never;
	url: '/api/login/';
};

export type LoginPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginPostError = LoginPostErrors[keyof LoginPostErrors];

export type LoginPostResponses = {
	/**
	 * Successful Response
	 */
	200: Tokens;
};

export type LoginPostResponse = LoginPostResponses[keyof LoginPostResponses];

export type LoginRefreshTokenPostData = {
	body?: never;
	path?: never;
	query: {
		/**
		 * Refresh Token
		 */
		refresh_token: string;
	};
	url: '/api/login/refresh-token/';
};

export type LoginRefreshTokenPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginRefreshTokenPostError =
	LoginRefreshTokenPostErrors[keyof LoginRefreshTokenPostErrors];

export type LoginRefreshTokenPostResponses = {
	/**
	 * Successful Response
	 */
	200: Tokens;
};

export type LoginRefreshTokenPostResponse =
	LoginRefreshTokenPostResponses[keyof LoginRefreshTokenPostResponses];

export type VerifyAccountTokenPutData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/verify/account/{token}/';
};

export type VerifyAccountTokenPutErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type VerifyAccountTokenPutError =
	VerifyAccountTokenPutErrors[keyof VerifyAccountTokenPutErrors];

export type VerifyAccountTokenPutResponses = {
	/**
	 * Response Verify Account Api Verify Account  Token   Put
	 *
	 * Successful Response
	 */
	200: string;
};

export type VerifyAccountTokenPutResponse =
	VerifyAccountTokenPutResponses[keyof VerifyAccountTokenPutResponses];

export type ForgotPasswordPostData = {
	body: BodyForgotPasswordApiForgotPasswordPost;
	path?: never;
	query?: never;
	url: '/api/forgot/password/';
};

export type ForgotPasswordPostErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ForgotPasswordPostError = ForgotPasswordPostErrors[keyof ForgotPasswordPostErrors];

export type ForgotPasswordPostResponses = {
	/**
	 * Response Forgot Password Api Forgot Password  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ForgotPasswordPostResponse =
	ForgotPasswordPostResponses[keyof ForgotPasswordPostResponses];

export type ResetPasswordTokenPostData = {
	body: BodyResetPasswordApiResetPasswordTokenPost;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/reset/password/{token}/';
};

export type ResetPasswordTokenPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ResetPasswordTokenPostError =
	ResetPasswordTokenPostErrors[keyof ResetPasswordTokenPostErrors];

export type ResetPasswordTokenPostResponses = {
	/**
	 * Response Reset Password Api Reset Password  Token   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ResetPasswordTokenPostResponse =
	ResetPasswordTokenPostResponses[keyof ResetPasswordTokenPostResponses];

export type ExpiredTokenGetData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/expired/{token}/';
};

export type ExpiredTokenGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ExpiredTokenGetError = ExpiredTokenGetErrors[keyof ExpiredTokenGetErrors];

export type ExpiredTokenGetResponses = {
	/**
	 * Response Is Token Expired Api Expired  Token   Get
	 *
	 * Successful Response
	 */
	200: boolean;
};

export type ExpiredTokenGetResponse = ExpiredTokenGetResponses[keyof ExpiredTokenGetResponses];

export type UsersSignupPostData = {
	body: BodyRegisterUserApiUsersSignupPost;
	path?: never;
	query?: never;
	url: '/api/users/signup/';
};

export type UsersSignupPostErrors = {
	/**
	 * Conflict
	 */
	409: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UsersSignupPostError = UsersSignupPostErrors[keyof UsersSignupPostErrors];

export type UsersSignupPostResponses = {
	/**
	 * Response Register User Api Users Signup  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type UsersSignupPostResponse = UsersSignupPostResponses[keyof UsersSignupPostResponses];

export type UsersMeDeleteData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/users/me/';
};

export type UsersMeDeleteErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type UsersMeDeleteError = UsersMeDeleteErrors[keyof UsersMeDeleteErrors];

export type UsersMeDeleteResponses = {
	/**
	 * Response Delete User Me Api Users Me  Delete
	 *
	 * Successful Response
	 */
	200: string;
};

export type UsersMeDeleteResponse = UsersMeDeleteResponses[keyof UsersMeDeleteResponses];

export type UsersMeGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/users/me/';
};

export type UsersMeGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type UsersMeGetError = UsersMeGetErrors[keyof UsersMeGetErrors];

export type UsersMeGetResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic;
};

export type UsersMeGetResponse = UsersMeGetResponses[keyof UsersMeGetResponses];

export type UsersMePatchData = {
	body: UserUpdateMe;
	path?: never;
	query?: never;
	url: '/api/users/me/';
};

export type UsersMePatchErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UsersMePatchError = UsersMePatchErrors[keyof UsersMePatchErrors];

export type UsersMePatchResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic;
};

export type UsersMePatchResponse = UsersMePatchResponses[keyof UsersMePatchResponses];

export type UsersMePasswordPatchData = {
	body: UpdatePassword;
	path?: never;
	query?: never;
	url: '/api/users/me/password/';
};

export type UsersMePasswordPatchErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UsersMePasswordPatchError =
	UsersMePasswordPatchErrors[keyof UsersMePasswordPatchErrors];

export type UsersMePasswordPatchResponses = {
	/**
	 * Response Update Password Me Api Users Me Password  Patch
	 *
	 * Successful Response
	 */
	200: string;
};

export type UsersMePasswordPatchResponse =
	UsersMePasswordPatchResponses[keyof UsersMePasswordPatchResponses];

export type CeleryResultTaskIdGetData = {
	body?: never;
	path: {
		/**
		 * Task Id
		 */
		task_id: string;
	};
	query?: never;
	url: '/api/celery/result/{task_id}/';
};

export type CeleryResultTaskIdGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CeleryResultTaskIdGetError =
	CeleryResultTaskIdGetErrors[keyof CeleryResultTaskIdGetErrors];

export type CeleryResultTaskIdGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type StorageAvailableSpaceGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/storage/available/space/';
};

export type StorageAvailableSpaceGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageAvailableSpaceGetError =
	StorageAvailableSpaceGetErrors[keyof StorageAvailableSpaceGetErrors];

export type StorageAvailableSpaceGetResponses = {
	/**
	 * Successful Response
	 */
	200: AvailableSpace;
};

export type StorageAvailableSpaceGetResponse =
	StorageAvailableSpaceGetResponses[keyof StorageAvailableSpaceGetResponses];

export type StorageItemsPathGetData = {
	body?: never;
	path: {
		/**
		 * Path
		 */
		path: string;
	};
	query?: {
		status?: FileFolderStatus;
	};
	url: '/api/storage/items/{path}/';
};

export type StorageItemsPathGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageItemsPathGetError = StorageItemsPathGetErrors[keyof StorageItemsPathGetErrors];

export type StorageItemsPathGetResponses = {
	/**
	 * Response Get Items Api Storage Items  Path   Get
	 *
	 * Successful Response
	 */
	200: Array<FileFolderPublic>;
};

export type StorageItemsPathGetResponse =
	StorageItemsPathGetResponses[keyof StorageItemsPathGetResponses];

export type StorageUploadMultiplePathPostData = {
	body: BodyUploadMultipleApiStorageUploadMultiplePathPost;
	path: {
		/**
		 * Path
		 */
		path: string;
	};
	query?: never;
	url: '/api/storage/upload/multiple/{path}/';
};

export type StorageUploadMultiplePathPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageUploadMultiplePathPostError =
	StorageUploadMultiplePathPostErrors[keyof StorageUploadMultiplePathPostErrors];

export type StorageUploadMultiplePathPostResponses = {
	/**
	 * Successful Response
	 */
	200: UploadFiles;
};

export type StorageUploadMultiplePathPostResponse =
	StorageUploadMultiplePathPostResponses[keyof StorageUploadMultiplePathPostResponses];

export type StorageCreateFolderFolderNamePathPostData = {
	body?: never;
	path: {
		/**
		 * Folder Name
		 */
		folder_name: string;
		/**
		 * Path
		 */
		path: string;
	};
	query?: never;
	url: '/api/storage/create/folder/{folder_name}/{path}/';
};

export type StorageCreateFolderFolderNamePathPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Conflict
	 */
	409: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageCreateFolderFolderNamePathPostError =
	StorageCreateFolderFolderNamePathPostErrors[keyof StorageCreateFolderFolderNamePathPostErrors];

export type StorageCreateFolderFolderNamePathPostResponses = {
	/**
	 * Response Create Folder Api Storage Create Folder  Folder Name   Path   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageCreateFolderFolderNamePathPostResponse =
	StorageCreateFolderFolderNamePathPostResponses[keyof StorageCreateFolderFolderNamePathPostResponses];

export type StorageMoveToRecycleFolderFolderIdPostData = {
	body?: never;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/storage/move-to-recycle/folder/{folder_id}/';
};

export type StorageMoveToRecycleFolderFolderIdPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageMoveToRecycleFolderFolderIdPostError =
	StorageMoveToRecycleFolderFolderIdPostErrors[keyof StorageMoveToRecycleFolderFolderIdPostErrors];

export type StorageMoveToRecycleFolderFolderIdPostResponses = {
	/**
	 * Response Delete Folder Api Storage Move To Recycle Folder  Folder Id   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageMoveToRecycleFolderFolderIdPostResponse =
	StorageMoveToRecycleFolderFolderIdPostResponses[keyof StorageMoveToRecycleFolderFolderIdPostResponses];

export type StorageMoveToRecycleFileFileIdPostData = {
	body?: never;
	path: {
		/**
		 * File Id
		 */
		file_id: string;
	};
	query?: never;
	url: '/api/storage/move-to-recycle/file/{file_id}/';
};

export type StorageMoveToRecycleFileFileIdPostErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageMoveToRecycleFileFileIdPostError =
	StorageMoveToRecycleFileFileIdPostErrors[keyof StorageMoveToRecycleFileFileIdPostErrors];

export type StorageMoveToRecycleFileFileIdPostResponses = {
	/**
	 * Response Delete File Api Storage Move To Recycle File  File Id   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageMoveToRecycleFileFileIdPostResponse =
	StorageMoveToRecycleFileFileIdPostResponses[keyof StorageMoveToRecycleFileFileIdPostResponses];

export type StorageDeletedItemsGetData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Folder Id
		 */
		folder_id?: string | null;
	};
	url: '/api/storage/deleted/items/';
};

export type StorageDeletedItemsGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageDeletedItemsGetError =
	StorageDeletedItemsGetErrors[keyof StorageDeletedItemsGetErrors];

export type StorageDeletedItemsGetResponses = {
	/**
	 * Response Get Deleted Items Api Storage Deleted Items  Get
	 *
	 * Successful Response
	 */
	200: Array<FileFolderPublic>;
};

export type StorageDeletedItemsGetResponse =
	StorageDeletedItemsGetResponses[keyof StorageDeletedItemsGetResponses];

export type HealthcheckGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/healthcheck/';
};

export type HealthcheckGetResponses = {
	/**
	 * Successful Response
	 */
	200: HealthCheck;
};

export type HealthcheckGetResponse = HealthcheckGetResponses[keyof HealthcheckGetResponses];
