// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AvailableSpace
 */
export type AvailableSpace = {
	/**
	 * Total
	 */
	total: number;
	/**
	 * Used
	 */
	used: number;
	/**
	 * Available
	 */
	available: number;
};

/**
 * Body_forgot_password_api_v1_forgot_password__post
 */
export type BodyForgotPasswordApiV1ForgotPasswordPost = {
	/**
	 * Email
	 */
	email: string;
};

/**
 * Body_log_in_api_v1_login__post
 */
export type BodyLogInApiV1LoginPost = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * Body_reset_password_api_v1_reset_password__token___post
 */
export type BodyResetPasswordApiV1ResetPasswordTokenPost = {
	/**
	 * New Password
	 */
	new_password: string;
};

/**
 * Body_upload_file_api_v1_storage_upload__folder_id___post
 */
export type BodyUploadFileApiV1StorageUploadFolderIdPost = {
	/**
	 * File
	 */
	file: Blob | File;
};

/**
 * Breadcrumbs
 */
export type Breadcrumbs = {
	/**
	 * Folder Name
	 */
	folder_name: string;
	/**
	 * Folder Id
	 */
	folder_id: string;
};

/**
 * FilePublic
 */
export type FilePublic = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * Location
	 */
	location: string;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Size
	 */
	size: number;
	/**
	 * Owner
	 */
	owner: string;
	/**
	 * Modified At
	 */
	modified_at: string;
	/**
	 * Opened At
	 */
	opened_at: string;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Parent Id
	 */
	parent_id: string | null;
};

/**
 * FileUpdate
 */
export type FileUpdate = {
	/**
	 * Name
	 */
	name?: string | null;
};

/**
 * FolderPublic
 */
export type FolderPublic = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * Location
	 */
	location: string;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Size
	 */
	size: number;
	/**
	 * Owner
	 */
	owner: string;
	/**
	 * Modified At
	 */
	modified_at: string;
	/**
	 * Opened At
	 */
	opened_at: string;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Parent Id
	 */
	parent_id: string | null;
};

/**
 * FolderUpdate
 */
export type FolderUpdate = {
	/**
	 * Name
	 */
	name?: string | null;
};

/**
 * HTTPMessage
 */
export type HttpMessage = {
	/**
	 * Msg
	 */
	msg: string;
	/**
	 * Loc
	 */
	loc?: string | null;
	/**
	 * Meta
	 */
	meta?: {
		[key: string]: unknown;
	} | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
	/**
	 * Title
	 */
	title: string;
	/**
	 * Description
	 */
	description: string;
	/**
	 * Version
	 */
	version: string;
};

/**
 * NewFolder
 */
export type NewFolder = {
	/**
	 * Name
	 */
	name: string;
};

/**
 * Token
 */
export type Token = {
	/**
	 * Access Token
	 */
	access_token: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * First Name
	 */
	first_name: string;
	/**
	 * Last Name
	 */
	last_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Is Verified
	 */
	is_verified?: boolean;
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean;
	/**
	 * Id
	 */
	id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
	/**
	 * First Name
	 */
	first_name: string;
	/**
	 * Last Name
	 */
	last_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
};

export type SignupPostData = {
	body: UserRegister;
	path?: never;
	query?: {
		/**
		 * Locale
		 */
		locale?: string;
	};
	url: '/api/v1/signup/';
};

export type SignupPostErrors = {
	/**
	 * Conflict
	 */
	409: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SignupPostError = SignupPostErrors[keyof SignupPostErrors];

export type SignupPostResponses = {
	/**
	 * Response Sign Up Api V1 Signup  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type SignupPostResponse = SignupPostResponses[keyof SignupPostResponses];

export type LoginPostData = {
	body: BodyLogInApiV1LoginPost;
	path?: never;
	query?: never;
	url: '/api/v1/login/';
};

export type LoginPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginPostError = LoginPostErrors[keyof LoginPostErrors];

export type LoginPostResponses = {
	/**
	 * Successful Response
	 */
	200: Token;
};

export type LoginPostResponse = LoginPostResponses[keyof LoginPostResponses];

export type VerifyAccountTokenPutData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/verify/account/{token}/';
};

export type VerifyAccountTokenPutErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type VerifyAccountTokenPutError =
	VerifyAccountTokenPutErrors[keyof VerifyAccountTokenPutErrors];

export type VerifyAccountTokenPutResponses = {
	/**
	 * Response Verify Account Api V1 Verify Account  Token   Put
	 *
	 * Successful Response
	 */
	200: string;
};

export type VerifyAccountTokenPutResponse =
	VerifyAccountTokenPutResponses[keyof VerifyAccountTokenPutResponses];

export type ForgotPasswordPostData = {
	body: BodyForgotPasswordApiV1ForgotPasswordPost;
	path?: never;
	query?: {
		/**
		 * Locale
		 */
		locale?: string;
	};
	url: '/api/v1/forgot/password/';
};

export type ForgotPasswordPostErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ForgotPasswordPostError = ForgotPasswordPostErrors[keyof ForgotPasswordPostErrors];

export type ForgotPasswordPostResponses = {
	/**
	 * Response Forgot Password Api V1 Forgot Password  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ForgotPasswordPostResponse =
	ForgotPasswordPostResponses[keyof ForgotPasswordPostResponses];

export type ResetPasswordTokenPostData = {
	body: BodyResetPasswordApiV1ResetPasswordTokenPost;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/reset/password/{token}/';
};

export type ResetPasswordTokenPostErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ResetPasswordTokenPostError =
	ResetPasswordTokenPostErrors[keyof ResetPasswordTokenPostErrors];

export type ResetPasswordTokenPostResponses = {
	/**
	 * Response Reset Password Api V1 Reset Password  Token   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type ResetPasswordTokenPostResponse =
	ResetPasswordTokenPostResponses[keyof ResetPasswordTokenPostResponses];

export type ExpiredTokenGetData = {
	body?: never;
	path: {
		/**
		 * Token
		 */
		token: string;
	};
	query?: never;
	url: '/api/v1/expired/{token}/';
};

export type ExpiredTokenGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ExpiredTokenGetError = ExpiredTokenGetErrors[keyof ExpiredTokenGetErrors];

export type ExpiredTokenGetResponses = {
	/**
	 * Response Is Token Expired Api V1 Expired  Token   Get
	 *
	 * Successful Response
	 */
	200: boolean;
};

export type ExpiredTokenGetResponse = ExpiredTokenGetResponses[keyof ExpiredTokenGetResponses];

export type UsersMeGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/users/me/';
};

export type UsersMeGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type UsersMeGetError = UsersMeGetErrors[keyof UsersMeGetErrors];

export type UsersMeGetResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic;
};

export type UsersMeGetResponse = UsersMeGetResponses[keyof UsersMeGetResponses];

export type StorageFoldersFolderIdGetData = {
	body?: never;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/folders/{folder_id}/';
};

export type StorageFoldersFolderIdGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageFoldersFolderIdGetError =
	StorageFoldersFolderIdGetErrors[keyof StorageFoldersFolderIdGetErrors];

export type StorageFoldersFolderIdGetResponses = {
	/**
	 * Response Get Folders In Folder Api V1 Storage Folders  Folder Id   Get
	 *
	 * Successful Response
	 */
	200: Array<FolderPublic>;
};

export type StorageFoldersFolderIdGetResponse =
	StorageFoldersFolderIdGetResponses[keyof StorageFoldersFolderIdGetResponses];

export type StorageBreadcrumbsFolderIdGetData = {
	body?: never;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/breadcrumbs/{folder_id}/';
};

export type StorageBreadcrumbsFolderIdGetErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageBreadcrumbsFolderIdGetError =
	StorageBreadcrumbsFolderIdGetErrors[keyof StorageBreadcrumbsFolderIdGetErrors];

export type StorageBreadcrumbsFolderIdGetResponses = {
	/**
	 * Response Get Folder Breadcrumbs Api V1 Storage Breadcrumbs  Folder Id   Get
	 *
	 * Successful Response
	 */
	200: Array<Breadcrumbs>;
};

export type StorageBreadcrumbsFolderIdGetResponse =
	StorageBreadcrumbsFolderIdGetResponses[keyof StorageBreadcrumbsFolderIdGetResponses];

export type StorageFolderRootGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/storage/folder/root/';
};

export type StorageFolderRootGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageFolderRootGetError =
	StorageFolderRootGetErrors[keyof StorageFolderRootGetErrors];

export type StorageFolderRootGetResponses = {
	/**
	 * Successful Response
	 */
	200: FolderPublic;
};

export type StorageFolderRootGetResponse =
	StorageFolderRootGetResponses[keyof StorageFolderRootGetResponses];

export type StorageFolderRootPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/storage/folder/root/';
};

export type StorageFolderRootPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageFolderRootPostError =
	StorageFolderRootPostErrors[keyof StorageFolderRootPostErrors];

export type StorageFolderRootPostResponses = {
	/**
	 * Response Create Root Folder Api V1 Storage Folder Root  Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageFolderRootPostResponse =
	StorageFolderRootPostResponses[keyof StorageFolderRootPostResponses];

export type StorageFolderIdPostData = {
	body: NewFolder;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/{folder_id}/';
};

export type StorageFolderIdPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageFolderIdPostError = StorageFolderIdPostErrors[keyof StorageFolderIdPostErrors];

export type StorageFolderIdPostResponses = {
	/**
	 * Response Create Folder Api V1 Storage  Folder Id   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageFolderIdPostResponse =
	StorageFolderIdPostResponses[keyof StorageFolderIdPostResponses];

export type StorageRenameFolderFolderIdPatchData = {
	body: FolderUpdate;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/rename/folder/{folder_id}/';
};

export type StorageRenameFolderFolderIdPatchErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageRenameFolderFolderIdPatchError =
	StorageRenameFolderFolderIdPatchErrors[keyof StorageRenameFolderFolderIdPatchErrors];

export type StorageRenameFolderFolderIdPatchResponses = {
	/**
	 * Response Rename Folder Api V1 Storage Rename Folder  Folder Id   Patch
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageRenameFolderFolderIdPatchResponse =
	StorageRenameFolderFolderIdPatchResponses[keyof StorageRenameFolderFolderIdPatchResponses];

export type StorageSuggestedFoldersGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/storage/suggested/folders/';
};

export type StorageSuggestedFoldersGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageSuggestedFoldersGetError =
	StorageSuggestedFoldersGetErrors[keyof StorageSuggestedFoldersGetErrors];

export type StorageSuggestedFoldersGetResponses = {
	/**
	 * Response Get Suggested Folders Api V1 Storage Suggested Folders  Get
	 *
	 * Successful Response
	 */
	200: Array<FolderPublic>;
};

export type StorageSuggestedFoldersGetResponse =
	StorageSuggestedFoldersGetResponses[keyof StorageSuggestedFoldersGetResponses];

export type StorageSuggestedFilesGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/storage/suggested/files/';
};

export type StorageSuggestedFilesGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageSuggestedFilesGetError =
	StorageSuggestedFilesGetErrors[keyof StorageSuggestedFilesGetErrors];

export type StorageSuggestedFilesGetResponses = {
	/**
	 * Response Get Suggested Files Api V1 Storage Suggested Files  Get
	 *
	 * Successful Response
	 */
	200: Array<FolderPublic>;
};

export type StorageSuggestedFilesGetResponse =
	StorageSuggestedFilesGetResponses[keyof StorageSuggestedFilesGetResponses];

export type StorageFilesFolderIdGetData = {
	body?: never;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/files/{folder_id}/';
};

export type StorageFilesFolderIdGetErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageFilesFolderIdGetError =
	StorageFilesFolderIdGetErrors[keyof StorageFilesFolderIdGetErrors];

export type StorageFilesFolderIdGetResponses = {
	/**
	 * Response Get Files In Folder Api V1 Storage Files  Folder Id   Get
	 *
	 * Successful Response
	 */
	200: Array<FilePublic>;
};

export type StorageFilesFolderIdGetResponse =
	StorageFilesFolderIdGetResponses[keyof StorageFilesFolderIdGetResponses];

export type StorageUploadFolderIdPostData = {
	body: BodyUploadFileApiV1StorageUploadFolderIdPost;
	path: {
		/**
		 * Folder Id
		 */
		folder_id: string;
	};
	query?: never;
	url: '/api/v1/storage/upload/{folder_id}/';
};

export type StorageUploadFolderIdPostErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageUploadFolderIdPostError =
	StorageUploadFolderIdPostErrors[keyof StorageUploadFolderIdPostErrors];

export type StorageUploadFolderIdPostResponses = {
	/**
	 * Response Upload File Api V1 Storage Upload  Folder Id   Post
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageUploadFolderIdPostResponse =
	StorageUploadFolderIdPostResponses[keyof StorageUploadFolderIdPostResponses];

export type StorageFileFileIdDeleteData = {
	body?: never;
	path: {
		/**
		 * File Id
		 */
		file_id: string;
	};
	query?: never;
	url: '/api/v1/storage/file/{file_id}/';
};

export type StorageFileFileIdDeleteErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageFileFileIdDeleteError =
	StorageFileFileIdDeleteErrors[keyof StorageFileFileIdDeleteErrors];

export type StorageFileFileIdDeleteResponses = {
	/**
	 * Response Delete File Api V1 Storage File  File Id   Delete
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageFileFileIdDeleteResponse =
	StorageFileFileIdDeleteResponses[keyof StorageFileFileIdDeleteResponses];

export type StorageMoveToTrashFileFileIdPatchData = {
	body?: never;
	path: {
		/**
		 * File Id
		 */
		file_id: string;
	};
	query?: never;
	url: '/api/v1/storage/move-to-trash/file/{file_id}/';
};

export type StorageMoveToTrashFileFileIdPatchErrors = {
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageMoveToTrashFileFileIdPatchError =
	StorageMoveToTrashFileFileIdPatchErrors[keyof StorageMoveToTrashFileFileIdPatchErrors];

export type StorageMoveToTrashFileFileIdPatchResponses = {
	/**
	 * Response Move File To Trash Api V1 Storage Move To Trash File  File Id   Patch
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageMoveToTrashFileFileIdPatchResponse =
	StorageMoveToTrashFileFileIdPatchResponses[keyof StorageMoveToTrashFileFileIdPatchResponses];

export type StorageRenameFileFileIdPatchData = {
	body: FileUpdate;
	path: {
		/**
		 * File Id
		 */
		file_id: string;
	};
	query?: never;
	url: '/api/v1/storage/rename/file/{file_id}/';
};

export type StorageRenameFileFileIdPatchErrors = {
	/**
	 * Bad Request
	 */
	400: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StorageRenameFileFileIdPatchError =
	StorageRenameFileFileIdPatchErrors[keyof StorageRenameFileFileIdPatchErrors];

export type StorageRenameFileFileIdPatchResponses = {
	/**
	 * Response Rename File Api V1 Storage Rename File  File Id   Patch
	 *
	 * Successful Response
	 */
	200: string;
};

export type StorageRenameFileFileIdPatchResponse =
	StorageRenameFileFileIdPatchResponses[keyof StorageRenameFileFileIdPatchResponses];

export type StorageAvailableSpaceGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/storage/available/space/';
};

export type StorageAvailableSpaceGetErrors = {
	/**
	 * Unauthorized
	 */
	401: HttpMessage;
	/**
	 * Forbidden
	 */
	403: HttpMessage;
	/**
	 * Not Found
	 */
	404: HttpMessage;
};

export type StorageAvailableSpaceGetError =
	StorageAvailableSpaceGetErrors[keyof StorageAvailableSpaceGetErrors];

export type StorageAvailableSpaceGetResponses = {
	/**
	 * Successful Response
	 */
	200: AvailableSpace;
};

export type StorageAvailableSpaceGetResponse =
	StorageAvailableSpaceGetResponses[keyof StorageAvailableSpaceGetResponses];

export type HealthcheckGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/healthcheck/';
};

export type HealthcheckGetResponses = {
	/**
	 * Successful Response
	 */
	200: HealthCheck;
};

export type HealthcheckGetResponse = HealthcheckGetResponses[keyof HealthcheckGetResponses];
