"""Store original folder in folders for restore operation

Revision ID: 064f03038a3c
Revises: 26c68b3a674c
Create Date: 2026-03-09 17:08:53.387794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "064f03038a3c"
down_revision: Union[str, Sequence[str], None] = "26c68b3a674c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folder", sa.Column("original_parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "folder", "folder", ["original_parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folder", type_="foreignkey")
    op.drop_column("folder", "original_parent_id")
    # ### end Alembic commands ###
