"""Store original folder in files for restore operation

Revision ID: 26c68b3a674c
Revises: 40d7c68f831c
Create Date: 2026-03-09 16:25:11.777968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26c68b3a674c"
down_revision: Union[str, Sequence[str], None] = "40d7c68f831c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("original_folder_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "file", "folder", ["original_folder_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="foreignkey")
    op.drop_column("file", "original_folder_id")
    # ### end Alembic commands ###
