"""User id in folder could be null due to the fact that the root folder is shared

Revision ID: 38caea246d15
Revises: e832373507ac
Create Date: 2026-02-21 10:48:34.737919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38caea246d15"
down_revision: Union[str, Sequence[str], None] = "e832373507ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("folder", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("folder", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
