"""EncryptedFile and EncryptedFolder tables

Revision ID: 3dfca32df443
Revises: d9a17d08ce84
Create Date: 2026-04-28 20:41:29.458422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "3dfca32df443"
down_revision: Union[str, Sequence[str], None] = "d9a17d08ce84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encryptedfolder",
        sa.Column("encrypted_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("iv", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="folderstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("original_parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_parent_id"],
            ["encryptedfolder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["encryptedfolder.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "encryptedfile",
        sa.Column("encrypted_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("iv", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "encrypted_name_iv", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("storage_id", sa.Uuid(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="filestatus", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("original_parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_parent_id"],
            ["encryptedfolder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["encryptedfolder.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("encryptedfile")
    op.drop_table("encryptedfolder")
    # ### end Alembic commands ###
