"""Parent id folder ondelete cascade and fix enum casting

Revision ID: 40d7c68f831c
Revises: 5d0217eef010
Create Date: 2026-02-27 17:26:21.567811
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "40d7c68f831c"
down_revision: Union[str, Sequence[str], None] = "5d0217eef010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE filefolderstatus AS ENUM ('PENDING', 'UPLOADED', 'FAILED', 'DELETED');"
    )
    op.alter_column(
        "file",
        "status",
        type_=sa.Text(),
        existing_type=postgresql.ENUM(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filestatus"
        ),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    op.alter_column(
        "file",
        "status",
        type_=sa.Enum(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filefolderstatus"
        ),
        postgresql_using="status::filefolderstatus",
        existing_nullable=False,
    )
    op.alter_column(
        "folder",
        "status",
        type_=sa.Text(),
        existing_type=postgresql.ENUM(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filestatus"
        ),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    op.alter_column(
        "folder",
        "status",
        type_=sa.Enum(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filefolderstatus"
        ),
        postgresql_using="status::filefolderstatus",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("folder_parent_id_fkey"), "folder", type_="foreignkey")
    op.create_foreign_key(
        None, "folder", "folder", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folder", type_="foreignkey")
    op.create_foreign_key(
        op.f("folder_parent_id_fkey"), "folder", "folder", ["parent_id"], ["id"]
    )
    op.alter_column(
        "folder",
        "status",
        type_=sa.Text(),
        existing_type=sa.Enum(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filefolderstatus"
        ),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    op.alter_column(
        "folder",
        "status",
        type_=postgresql.ENUM(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filestatus"
        ),
        postgresql_using="status::filestatus",
        existing_nullable=False,
    )
    op.alter_column(
        "file",
        "status",
        type_=sa.Text(),
        existing_type=sa.Enum(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filefolderstatus"
        ),
        postgresql_using="status::text",
        existing_nullable=False,
    )
    op.alter_column(
        "file",
        "status",
        type_=postgresql.ENUM(
            "PENDING", "UPLOADED", "FAILED", "DELETED", name="filestatus"
        ),
        postgresql_using="status::filestatus",
        existing_nullable=False,
    )
    op.execute("DROP TYPE filefolderstatus;")
    # ### end Alembic commands ###
