"""Status field added to Folder table

Revision ID: 5d0217eef010
Revises: 3b04f3e92d45
Create Date: 2026-02-22 21:28:36.187042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d0217eef010"
down_revision: Union[str, Sequence[str], None] = "3b04f3e92d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folder",
        sa.Column(
            "status",
            sa.Enum("PENDING", "UPLOADED", "FAILED", "DELETED", name="filestatus"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folder", "status")
    # ### end Alembic commands ###
