"""User last name optional

Revision ID: 69f7910de621
Revises: 82087bd915db
Create Date: 2026-07-08 12:10:59.697767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69f7910de621"
down_revision: Union[str, Sequence[str], None] = "82087bd915db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
