"""add trash restore support with original_parent_id

Revision ID: 82087bd915db
Revises: 04397a18b07e
Create Date: 2026-04-17 14:50:53.516469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82087bd915db"
down_revision: Union[str, Sequence[str], None] = "04397a18b07e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("original_parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "file", "folder", ["original_parent_id"], ["id"])
    op.add_column("folder", sa.Column("original_parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "folder", "folder", ["original_parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folder", type_="foreignkey")
    op.drop_column("folder", "original_parent_id")
    op.drop_constraint(None, "file", type_="foreignkey")
    op.drop_column("file", "original_parent_id")
    # ### end Alembic commands ###
