"""Store original folder in folders for restore operation

Revision ID: 931b4ac4cfad
Revises: a0f7be18eec7
Create Date: 2026-03-09 21:06:33.741010

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "931b4ac4cfad"
down_revision: Union[str, Sequence[str], None] = "a0f7be18eec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
