"""Vault hashed password attribute

Revision ID: a04c9ca7c462
Revises: 3dfca32df443
Create Date: 2026-05-09 11:21:47.204900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a04c9ca7c462"
down_revision: Union[str, Sequence[str], None] = "3dfca32df443"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password_vault", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.execute(
        """
        UPDATE "user"
        SET hashed_password_vault = hashed_password
        """
    )
    op.alter_column(
        "user",
        sa.Column(
            "hashed_password_vault", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashed_password_vault")
    # ### end Alembic commands ###
