"""Store original folder in folders for restore operation

Revision ID: a0f7be18eec7
Revises: 064f03038a3c
Create Date: 2026-03-09 21:04:54.273411

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a0f7be18eec7"
down_revision: Union[str, Sequence[str], None] = "064f03038a3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
