"""Metadata tables creation

Revision ID: be0edbfe6707
Revises: c40056d4e75e
Create Date: 2026-02-09 07:28:38.942317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "be0edbfe6707"
down_revision: Union[str, Sequence[str], None] = "c40056d4e75e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storagemetadatafield",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "STRING", "BOOL", "INTEGER", "FLOAT", name="storagemetadatafieldtype"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storagemetadatafieldlink",
        sa.Column(
            "type",
            sa.Enum(
                "STRING", "BOOL", "INTEGER", "FLOAT", name="storagemetadatafieldtype"
            ),
            nullable=False,
        ),
        sa.Column("value_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value_bool", sa.Boolean(), nullable=True),
        sa.Column("value_int", sa.Integer(), nullable=True),
        sa.Column("value_float", sa.Float(), nullable=True),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("metadata_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["metadata_id"], ["storagemetadatafield.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("file_id", "metadata_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storagemetadatafieldlink")
    op.drop_table("storagemetadatafield")
    # ### end Alembic commands ###
