"""Adding self-referencing folder

Revision ID: c40056d4e75e
Revises: 741c0ab8ca06
Create Date: 2026-02-09 07:08:07.920942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c40056d4e75e"
down_revision: Union[str, Sequence[str], None] = "741c0ab8ca06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folder", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "folder", "folder", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folder", type_="foreignkey")
    op.drop_column("folder", "parent_id")
    # ### end Alembic commands ###
