"""Parent id folder ondelete cascade

Revision ID: ce975e8b8ad1
Revises: fa24a4465652
Create Date: 2026-02-24 19:02:07.061165

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ce975e8b8ad1"
down_revision: Union[str, Sequence[str], None] = "fa24a4465652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("folder_parent_id_fkey"), "folder", type_="foreignkey")
    op.create_foreign_key(
        None, "folder", "folder", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folder", type_="foreignkey")
    op.create_foreign_key(
        op.f("folder_parent_id_fkey"), "folder", "folder", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
