"""UserKey table

Revision ID: d9a17d08ce84
Revises: 82087bd915db
Create Date: 2026-04-24 17:27:56.672984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d9a17d08ce84"
down_revision: Union[str, Sequence[str], None] = "82087bd915db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userkey",
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "encrypted_private_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "encrypted_private_key_recovery",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("iv", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("iv_recovery", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pbkdf2_salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "user",
        sa.Column(
            "has_seen_personal_vault",
            sa.Boolean(),
            nullable=False,
            server_default="False",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_seen_personal_vault")
    op.drop_table("userkey")
    # ### end Alembic commands ###
