"""Folder stored name could be null

Revision ID: e832373507ac
Revises: d6f1ae2ac7a4
Create Date: 2026-02-21 10:04:05.668184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e832373507ac"
down_revision: Union[str, Sequence[str], None] = "d6f1ae2ac7a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folder", "stored_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folder", "stored_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
